permissions:
  tpa: luckytpa.tpa # This goes for /tpahere too
  tpaccept: luckytpa.tpaccept
  tpdeny: luckytpa.tpdeny
  tp: luckytpa.tp
  tphere: luckytpa.tphere
  bypass-delay: luckytpa.bypassdelay

settings:
  time-delay: false
  time-to-teleport: 5 # This is in seconds
  cooldown: 30 # This is in seconds
  cooldown-msg: "&c&lLuckyTPA &7» &fYou are sending too many requests!"

messages:
  sent-tpa: "&c&lLuckyTPA &7» &fYou have requested to teleport to &b%player%"
  received-tpa: "&c&lLuckyTPA &7» &fYou have received a teleport request from &b%player%"
  sent-tpahere: "&c&lLuckyTPA &7» &fYou have requested to teleport &b%player% &fto you"
  received-tpahere: "&c&lLuckyTPA &7» &fYou have received a teleport request from &b%player% &fto teleport to them"
  accept: "&a&l[ACCEPT]"
  deny: "&c&l[DENY]"
  no-permission: "&c&lLuckyTPA &7» &cYou don't have permission to run this command!"
  console-cmd: "&c&lLuckyTPA &7» &cOnly players can run this command!"
  player-offline: "&c&lLuckyTPA &7» &fPlayer is offline or doesn't exist"
  no-requests: "&c&lLuckyTPA &7» &fYou don't have any requests"
  you-accepted: "&c&lLuckyTPA &7» &fYou have &aaccepted &fthe teleport request"
  player-accepted: "&c&lLuckyTPA &7» &b%player% &fhas &aaccepted &fyour request"
  player-accepted-timer: "&c&lLuckyTPA &7» &b%player% &fhas &aaccepted your request, teleporting in &c%time% &fseconds"
  you-denied: "&c&lLuckyTPA &7» &fYou have &cdenied &fthe teleport request"
  player-denied: "&c&lLuckyTPA &7» &b%player% &fhas &cdenied &fyour request"
  tp-msg: "&c&lLuckyTPA &7» &fYou have teleported to &b%player%"
  tphere-msg: "&c&lLuckyTPA &7» &fYou have teleported &b%player% &fto you"
  cant-tp-to-self: "&c&lLuckyTPA &7» &cSilly! You can't teleport to yourself"

usage-messages:
  tpa: "&c&lLuckyTPA &7» &6/tpa [name]"
  tpahere: "&c&lLuckyTPA &7» &6/tpahere [name]"
  tp: "&c&lLuckyTPA &7» &6/tp [name]"
  tphere: "&c&lLuckyTPA &7» &6/tphere [name]"